language: python
python:
  - "3.3"
install:
  - pip install -r requirements.txt
script:
  - invoke tests --suite unit
  - invoke tests --suite functional
  - invoke tests --suite coverage
branches:
  only:
    - master
