language: python
python:
  - "3.3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'CREATE DATABASE warehouse;' -U postgres
script:
  - invoke tests --suite unit
  - invoke tests --suite functional
  - invoke tests --suite coverage
after_success:
  - coveralls
branches:
  only:
    - master
