# Warehouse settings
COMMON: &common
    SITE_NAME: Warehouse (Dev)
    SECRET_KEY: "insecure development secret key"

    DATABASES:
        default:
            ENGINE: django.db.backends.postgresql_psycopg2
            NAME: warehouse

DEVELOPMENT: &development
    <<: *common

    DEBUG: true
    TEMPLATE_DEBUG: true

PRODUCTION: &production
    <<: *common
